import { THREE, CANNON, boxMesh, mats, world, controls, state, distXZ } from './core.js';
export const furniture=[];
function add(name,x,y,z,sx,sy,sz,mat){const m=boxMesh(x,y,z,sx,sy,sz,mat,false);const body=new CANNON.Body({mass:Math.max(1,sx*sy*sz),shape:new CANNON.Box(new CANNON.Vec3(sx/2,sy/2,sz/2)),position:new CANNON.Vec3(x,y,z),linearDamping:.25,angularDamping:.55});world.addBody(body);m.userData={body,name,carried:false,stolen:false,home:false};furniture.push(m);}
add('chair',-14,.9,-9,1.2,1.8,1.2,mats.red); add('lamp',-12,1.3,-4,.65,2.6,.65,mats.white); add('table',-15,1.5,5,3,3,1.8,mats.wood); add('chair',-12,.9,7,1.2,1.8,1.2,mats.green); add('cabinet',12,2,-11,2.8,4,1.2,mats.wood); add('sofa',14,1.5,-4,4,2.2,1.5,mats.red); add('chair',13,.9,5,1.2,1.8,1.2,mats.green);
function noise(pos,amount){if(globalThis.neighborAI) globalThis.neighborAI.hear(pos,amount);}
export function interactFurniture(){const p=controls.getObject().position;let best=null,bd=2.4;for(const f of furniture){if(f.userData.carried||f.userData.home)continue;const d=distXZ(p,f.position);if(d<bd){bd=d;best=f;}}if(best){state.carried=best;best.userData.carried=true;best.userData.body.type=CANNON.Body.KINEMATIC;best.userData.body.mass=0;noise(p,2);}}
export function dropFurniture(){const f=state.carried;if(!f)return;state.carried=null;f.userData.carried=false;const b=f.userData.body;b.type=CANNON.Body.DYNAMIC;b.mass=Math.max(1,f.geometry.parameters.width*f.geometry.parameters.height*f.geometry.parameters.depth*2);b.updateMassProperties();const p=controls.getObject().position;b.position.set(p.x,Math.max(1,f.geometry.parameters.height/2),p.z-1.3);b.velocity.set(0,0,0);noise(b.position,18);}
export function updateFurniture(){for(const f of furniture){const b=f.userData.body;if(f.userData.carried){const p=controls.getObject().position;const forward=new THREE.Vector3();controls.getDirection(forward);const t=p.clone().add(forward.multiplyScalar(1.6));b.position.set(t.x,Math.max(1,t.y-.2),t.z);b.velocity.set(0,0,0);b.angularVelocity.set(0,0,0);}f.position.copy(b.position);f.quaternion.copy(b.quaternion);}}
export function checkDelivery(){const f=state.carried;if(!f)return;const p=controls.getObject().position;if(p.z>12&&Math.abs(p.x)<6){state.carried=null;f.userData.carried=false;f.userData.stolen=true;f.userData.home=true;f.userData.body.type=CANNON.Body.KINEMATIC;f.position.set(-30,2+state.stolen*.8,12);state.stolen++;document.getElementById('stolen').textContent=state.stolen;if(globalThis.neighborAI)globalThis.neighborAI.worry=Math.min(100,globalThis.neighborAI.worry+12);if(state.stolen===furniture.length)document.getElementById('status').textContent='You robbed the house! You win!';}}
